Update axiom-scan

diff --git a/interact/axiom-scan b/interact/axiom-scan
--- a/interact/axiom-scan
+++ b/interact/axiom-scan
@@ -68,10 +68,10 @@ function parse_module() {
 function help(){
 cat << EOF
 axiom-scan provides easy distribution of arbitrary binaries and scripts.
-axiom-scan splits and uploads user-provided input files (target lists), wordlists and configuration files to every instance.
-axiom-scan executes the same command across all instances, which can be found in the module.
-axiom-scan downloads and merges scan output in a variety of different ways, specified in the module (folder, merged text file, csv etc).
-individual scans are executed in the background, inside a unique tmux session and scan working directory on the remote instances
+axiom-scan splits user-provided input files (target lists), wordlists and configuration files and uploads them to a unique scan working directory on the remote instance.
+axiom-scan combines user-provided command-line arguments with commands in the module to execute the final command on the remote instance.
+axiom-scan downloads and merges scan output in a variety of differnet formats, depening on the module's  the extention must be specified in the module (dir, txt, csv, xml).
+individual scanning operations are conducted inside a detacted tmux session (\$module+\$timestamp) with a unique scan working directory (/home/op/scan/\$module+\$timestamp) on the remote instances.
 
 Usage:
    axiom-scan inputfile.txt -m ffuf -w /home/op/wordlist-on-remote-instance
@@ -102,7 +102,6 @@ CONFIGURATIONS:
    --config string[]                     replace _config_ in module with user-provided configuration file (must be a configuration file on the remote instances)
    --local-config string[]               replace _config_ in module with user-provided local configuration file to upload (must be a local configuration file)
    --distribute-config string[]          replace _config_ in module with random config file in local folder (must be a path to a local folder containing multiple configuration files)
-
 
 OUTPUT:
    -o string[]          output as default (the first ext mentioned in the module) 
@@ -287,9 +286,22 @@ fi
 fi
 }
 
+###########################################################################################################
+#  divide the amount of files in a user-provided folder by how many instances are selected (axiom-select). 
+#  Equally distribute the files across the fleet.
+#
+split_folder(){
+split_directory="$1"
+i=1;
+for f in $split_directory/* ;
+do
+    instance="$(echo $instances | awk "{ print \$$i }")"
+    mkdir -p "$tmp/distribute_config/$instance";
+    cp "$f" "$tmp/distribute_config/$instance/config";
+    let i++;
+done
+}
 
-#split_folder(){
-#}
 ###########################################################################################################
 #  Merge the output in a certain way specified in the module or if the user specified -oX -oG or -oD it will overwrite the default (-o).
 #  If only supplying -o as an output argument via the command line, the output format will default to the first extension mentioned in the module.
@@ -539,7 +551,6 @@ do
             pass+=($i)
             pass+=($n)
         fi
-
         if [[ "$arg" == "--distribute-wordlist" ]] || [[ "$arg" == "-wD" ]]; then
             n=$((i+1))
             distribute_wordlist=$(echo ${!n})
@@ -588,7 +599,6 @@ do
         if  [[ "$set" != "true" ]]; then
             args="$args $arg"
         fi
-
     fi
 done
 
@@ -798,7 +808,6 @@ if [[ "$distribute_wordlist" != "false" ]]; then
     fi
 fi
 
-
 ###########################################################################################################
 #  Figure out what config to use 
 #
@@ -816,17 +825,6 @@ if [[ "$local_config" != "false" ]]; then
         exit 1
     fi
 fi
-if [[ "$distribute_config" != "false" ]]; then
-    if [[ -d "$distribute_config" ]]; then
-        distribute_config_filename="$(echo "$distribute_config" | tr '/' ' ' | awk '{ print $NF }')"
-        destination_config="/home/op/scan/$uid/$distribute_config_filename"
-        config_file="$destination_config"
-    else
-        echo -e "${Red}Error: local config folder to distribute not found '$distribute_config'...${Color_Off}"
-        exit 1
-    fi
-fi
-
 
 ###########################################################################################################
 #  If a one-shot module is used:
@@ -902,25 +900,23 @@ fi
 ###########################################################################################################
 #  If --distribuate-config is present in the command line, split the folder of config files and upload each config to every instance
 #
-
 if [[ "$distribute_config" != "false" ]]; then
 if [[ -d "$distribute_config" ]]; then
-    distribute_config_filename="$(echo "$distribute_config" | tr '/' ' ' | awk '{ print $NF }')"
+    distribute_config_filename="config"
     destination_config="/home/op/scan/$uid/$distribute_config_filename"
     config_file="$destination_config"
     mkdir -p $tmp/distribute_config/split
     mkdir -p $tmp/distribute_config/input
     cp "$tmp/selected.conf" "$tmp/distribute_config/selected.conf"
-    split_folder "$distribute_config_filename" "$total_instances" "$tmp/distribute_config"
-
-    $interlace_cmd_nobar -c "$AXIOM_PATH/interact/axiom-scp $tmp/distribute_config/input/_target_ _target_:$destination_wordlist --cache -F=$sshconfig >/dev/null 2>&1" 
-
+    split_folder $distribute_config
     echo -e "${BGreen}distributing folder of local config files${Color_Off}${Blue} : $distribute_config${Color_Off} to ${Blue}$destination_config...${Color_Off}"
-    interlace --no-bar --silent -threads $total_instances -tL "$tmp/selected.conf" -c "$AXIOM_PATH/interact/axiom-scp $distribute_config _target_:$destination_config --cache -F=$sshconfig >> /dev/null"
+    $interlace_cmd_nobar -c "$AXIOM_PATH/interact/axiom-scp $tmp/distribute_config/_target_/config _target_:$scan_dir/config --cache -F=$sshconfig >/dev/null 2>&1" 
     echo -e "${Green}local config uploaded successfully!${Color_Off}"
+    else
+        echo -e "${Red}Error: local config folder to distribute not found '$distribute_config'...${Color_Off}"
+        exit 1
+    fi
 fi
-fi
-
 
 ###########################################################################################################
 #  If a wordlist is specified add it to the command
@@ -1145,4 +1141,3 @@ wait $tailPID 2>/dev/null
 wait $downloaderPID 2>/dev/null
 stty sane
 tput init
-
